### ISSUE TITLE
Export to CSV fails

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/SDM_Tools#15]
> Running script ExportCSV...
 Traceback (most recent call last):
  File "<string>", line 456, in execute
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\pandas\core\frame.py", line 2133, in __getitem__
    return self._getitem_array(key)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\pandas\core\frame.py", line 2177, in _getitem_array
    indexer = self.loc._convert_to_indexer(key, axis=1)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\pandas\core\indexing.py", line 1269, in _convert_to_indexer
    .format(mask=objarr[mask]))
KeyError: "['UID'] not in index"
 Failed to execute (ExportCSV).

**Comment by ChristopherTracey** [comment]
@memoore told me not to use OID nor COMID.
