### ISSUE TITLE
field length error in step 2 in Aquatic Grouping tool.

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/SDM_Tools#20]
Nathan thought this was due to a lack of an RA field, but it might be something else.

```
Running script ExportCSV...
Traceback (most recent call last):  File "<string>", line 394, in execute  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\management.py", line 3577, in AddField    raise e  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\management.py", line 3574, in AddField    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\geoprocessing\_base.py", line 498, in <lambda>    return lambda *args: val(*gp_fixargs(args, True))arcgisscripting.ExecuteError: Failed to execute. Parameters are not valid. ERROR 000313: The length of Field Name must not be larger than 10Failed to execute (AddField).
 Failed to execute (ExportCSV).
```

**Comment by ChristopherTracey** [comment]
This appears to be the result of using a shapefile as an input layer.
