### ISSUE TITLE
COMID not found when trying to join to service areas

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/SDM_Tools#9]
```
Joining COMID
Traceback (most recent call last):
  File "<string>", line 245, in execute
  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\management.py", line 4827, in DeleteIdentical
    raise e
  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\management.py", line 4824, in DeleteIdentical
    retval = convertArcObjectToPythonObject(gp.DeleteIdentical_management(*gp_fixargs((in_dataset, fields, xy_tolerance, z_tolerance), True)))
  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\geoprocessing\_base.py", line 498, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.
 ERROR 000728: Field COMID does not exist within table
Failed to execute (DeleteIdentical).
 Failed to execute (AquaticGrouping).
```

**Comment by memoore** [comment]
I'll fix this tomorrow. I think it's an issue with the catchment dataset
calling comid 'featureid' or whatever.

**Comment by memoore** [comment]
This now works using the FEATUREID field.
